backend:
  name: git-gateway
  branch: svelte
collections:
  - name: FAQ
    label: FAQ
    folder: modules/faqs/
    create: true
    slug: "{{order}}-{{day}}-{{month}}-{{year}}-{{title}}"
    fields:
      - name: Category
        widget: "select"
        options:
          - { label: "Starting Out", value: "Starting Out" }
          - { label: "Building", value: "Building" }
          - { label: "Betaflight", value: "Betaflight" }
          - { label: "Video", value: "Video" }
          - { label: "Radio", value: "Radio" }
          - { label: "Hardware", value: "Hardware" }
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Question", name: "title", widget: "text"}
      - {label: "Answer", name: "answer", widget: "markdown"}

  - name: 5" Beginner Build
    label: 5" Beginner Build
    folder: modules/buildLists/5inchBeginner/
    create: true
    slug: "{{order}}-{{day}}-{{month}}-{{year}}-{{Category}}-{{title}}"
    fields:
      - label: Category
        name: Category
        widget: "select"
        options:
          - { label: "Frames", value: "Frames" }
          - { label: "Motors", value: "Motors" }
          - { label: "Flight Controllers", value: "Flight Controllers" }
          - { label: "ESCs", value: "ESCs" }
          - { label: "Video Transmitters", value: "Video Transmitters" }
      - label: Price Range
        name: color
        widget: "select"
        options:
          - { label: "Budget", value: "green" }
          - { label: "Mid-Range", value: "orange" }
          - { label: "High-end", value: "red" }
          - { label: "Varied", value: "violet" }
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Title", name: "title", widget: "text"}
      - {label: "Link", name: "link", widget: "text"}
      - {label: "Description", name: "text", widget: "text"}

      - {label: "Price", name: "price", widget: "text"}
      - {label: "Point 1", name: "point1", widget: "text", required: false}
      - {label: "Point 2", name: "point2", widget: "text", required: false}
      - {label: "Point 3", name: "point3", widget: "text", required: false}
      - {label: "Point 4", name: "point4", widget: "text", required: false}
      - {label: "Point 5", name: "point5", widget: "text", required: false}

  - name: 3" Cinewhoop Build
    label: 3" Cinewhoop Build
    folder: modules/buildLists/3inchCinewhoop/
    create: true
    slug: "{{order}}-{{day}}-{{month}}-{{year}}-{{Category}}-{{title}}"
    fields:
      - label: Category
        name: Category
        widget: "select"
        options:
          - { label: "Frames", value: "Frames" }
          - { label: "Motors", value: "Motors" }
          - { label: "Flight Controllers", value: "Flight Controllers" }
          - { label: "ESCs", value: "ESCs" }
          - { label: "AIOs", value: "AIOs" }
          - { label: "Video Transmitters", value: "Video Transmitters" }
      - label: Price Range
        name: color
        widget: "select"
        options:
          - { label: "Budget", value: "green" }
          - { label: "Mid-Range", value: "orange" }
          - { label: "High-end", value: "red" }
          - { label: "Varied", value: "violet" }
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Title", name: "title", widget: "text"}
      - {label: "Link", name: "link", widget: "text"}
      - {label: "Description", name: "text", widget: "text"}

      - {label: "Price", name: "price", widget: "text"}
      - {label: "Point 1", name: "point1", widget: "text", required: false}
      - {label: "Point 2", name: "point2", widget: "text", required: false}
      - {label: "Point 3", name: "point3", widget: "text", required: false}
      - {label: "Point 4", name: "point4", widget: "text", required: false}
      - {label: "Point 5", name: "point5", widget: "text", required: false}
    
media_folder: "/static/uploads/"
public_folder: "/static/uploads/"

# site_url: https://your-site.com
# display_url: https://your-site.com
# logo_url: https://your-site.com/images/logo.svg